# Generated by Django 3.2.9 on 2021-11-27 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_minute', models.DecimalField(decimal_places=2, max_digits=4)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prefix', models.CharField(max_length=10)),
                ('caller', models.ForeignKey(help_text='Customer who made the call', on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
